## Problem 5:

### a)

In [231]:
import numpy as np
import math

In [232]:
R = lambda t: np.array([[math.cos(t), -1*math.sin(t), 0.0], [math.sin(t), math.cos(t), 0.0], [0.0, 0.0, 1.0]])

In [233]:
r = R(np.pi/6)
r

array([[ 0.8660254, -0.5      ,  0.       ],
       [ 0.5      ,  0.8660254,  0.       ],
       [ 0.       ,  0.       ,  1.       ]])

In [234]:
r.T

array([[ 0.8660254,  0.5      ,  0.       ],
       [-0.5      ,  0.8660254,  0.       ],
       [ 0.       ,  0.       ,  1.       ]])

In [235]:
np.linalg.inv(r)

array([[ 0.8660254,  0.5      ,  0.       ],
       [-0.5      ,  0.8660254,  0.       ],
       [ 0.       ,  0.       ,  1.       ]])

In [236]:
np.linalg.det(r)

1.0

In [237]:
n = r[:,0]
s = r[:,1]
a = r[:,2]

In [238]:
np.linalg.norm(n)

1.0

In [239]:
np.linalg.norm(s)

1.0

In [240]:
np.linalg.norm(a)

1.0

In [241]:
np.dot(n,s)

0.0

In [242]:
np.dot(s,a)

0.0

In [243]:
np.dot(a,n)

0.0

### b) t = pi/3

In [244]:
r = R(np.pi/3)
r

array([[ 0.5      , -0.8660254,  0.       ],
       [ 0.8660254,  0.5      ,  0.       ],
       [ 0.       ,  0.       ,  1.       ]])

In [245]:
r.T

array([[ 0.5      ,  0.8660254,  0.       ],
       [-0.8660254,  0.5      ,  0.       ],
       [ 0.       ,  0.       ,  1.       ]])

In [246]:
np.linalg.inv(r)

array([[ 0.5      ,  0.8660254,  0.       ],
       [-0.8660254,  0.5      , -0.       ],
       [ 0.       ,  0.       ,  1.       ]])

In [247]:
np.linalg.det(r)

1.0

In [248]:
n = r[:,0]
s = r[:,1]
a = r[:,2]

In [249]:
np.linalg.norm(n)

1.0

In [250]:
np.linalg.norm(s)

1.0

In [251]:
np.linalg.norm(a)

1.0

In [252]:
np.dot(n,s)

0.0

In [253]:
np.dot(s,a)

0.0

In [254]:
np.dot(a,n)

0.0

### t = -pi/4

In [255]:
r = R(-1*np.pi/4)
r

array([[ 0.70710678,  0.70710678,  0.        ],
       [-0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [256]:
r.T

array([[ 0.70710678, -0.70710678,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [257]:
np.linalg.inv(r)

array([[ 0.70710678, -0.70710678,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [258]:
np.linalg.det(r)

1.0

In [259]:
n = r[:,0]
s = r[:,1]
a = r[:,2]

In [260]:
np.linalg.norm(n)

1.0

In [261]:
np.linalg.norm(s)

1.0

In [262]:
np.linalg.norm(a)

1.0

In [263]:
np.dot(n,s)

0.0

In [264]:
np.dot(s,a)

0.0

In [265]:
np.dot(a,n)

0.0